### ISSUE TITLE
pyproject.toml  [tool.pytest.ini_options] have no effect in uv run pytest

### ISSUE THREAD

**Issue by MrMegaMango** [pytest-dev/pytest-env#124]
![Image](https://github.com/user-attachments/assets/eb0fce26-5a41-4ce2-a7c6-429fa0a038e1)
![Image](https://github.com/user-attachments/assets/b19edcd4-9e88-4fff-97c7-a3f10a18ecbc)
uv run pytest services/api/core/tasks/tests/test_notifications.py
![Image](https://github.com/user-attachments/assets/670a48fd-6cce-4229-9e39-e9f3582efdde)

**Comment by The-Compiler** [comment]
You'll need to say a bit more than just the equivalent of "it doesn't work", as it seems to work just fine:

pyproject.toml:

```toml
[project]
name = "env-uv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "pytest-env>=1.1.5",
]

[tool.pytest.ini_options]
env = [
    "ENVVAR=test",
]
```

test_x.py:

```python
import os

def test_var():
    assert os.environ["ENVVAR"] == "test"
```

result:

```console
$ uv run pytest --no-header
============================= test session starts ==============================
collected 1 item                                                               

test_x.py .                                                              [100%]

============================== 1 passed in 0.00s ===============================
```
